---
title: "Entrega 6"
author: "Ángel García, Arnau Piferrer  y Guillem Serra"
format: html
editor: visual
---

Este es el [repositorio](https://github.com/GSMir/Entrega6) de GitHub en el que alojaremos todos los archivos relacionados con esta entrega.


```{r}
# Cargamos las librerías que hagan falta:

library(tools)
library(HSAUR2)
library(MVA)
library(ggplot2)
```

```{r}
# Cargamos nuestras matrices de distancias:

matrix_vh <- read.csv("ANIMALS-matrixVH.txt", header = FALSE, sep = " ")
matrix_sp <- read.csv("ANIMALS-matrixSP.txt", header = FALSE, sep = " ")
matrix_pm <- read.csv("ANIMALS-matrixPM.txt", header = FALSE, sep = " ")
```

```{r}
# Cargamos los datos del phylum de cada animal:

phylum_list <- read.table("fileListANIMAL_phylum.txt")
```


```{r}
# Aquí he querido asignar colores random a cada Phylum:

colores_predefinidos <- c("red", "blue", "green", "darkorange", "deepskyblue", "chartreuse", 
                          "darkorchid", "gold", "darkgreen", "royalblue", "brown", "grey", 
                          "pink", "navy")
```


```{r}
mds_result <- cmdscale(matrix_sp, k = 2)
```



```{r}
# Asegurándonos de que mds_result es un data frame y tiene nombres de fila

mds_data <- as.data.frame(mds_result)
mds_data$phylum <- phylum_list$V2
mds_data$phylum <- as.factor(mds_data$phylum)  # La he tenido que guardar como factor para que no petase luego el código.
```

```{r}
# Creamos el gráfico:

ggplot(mds_data, aes(x = V1, y = V2, color = phylum)) + 
  geom_point() +
  theme_minimal() +
  labs(title = "MDS Plot of VH Matrix by Phylum", x = "MDS Dim 1", y = "MDS Dim 2") +
  scale_color_manual(values = colores_predefinidos) # Esto usa una paleta de colores predefinida 
  
```
